// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/listings": {
            "get": {
                "description": "get all listings in database",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all listings",
                "operationId": "get-listings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListingsResponse"
                        }
                    }
                }
            }
        },
        "/api/user": {
            "get": {
                "description": "get user",
                "produces": [
                    "application/json"
                ],
                "summary": "Get user",
                "operationId": "get-user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserResponse"
                        }
                    }
                }
            }
        },
        "/api/user/likes": {
            "get": {
                "description": "get user likes",
                "produces": [
                    "application/json"
                ],
                "summary": "Get user likes",
                "operationId": "get-user-likes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetUserLikesResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "update user like",
                "produces": [
                    "application/json"
                ],
                "summary": "Update user like",
                "operationId": "update-user-like",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UpdateUserLikeResponse"
                        }
                    }
                }
            }
        },
        "/api/user/signout": {
            "get": {
                "description": "sign out",
                "produces": [
                    "application/json"
                ],
                "summary": "sign out",
                "operationId": "sign-out",
                "responses": {}
            }
        },
        "/api/user/verify": {
            "get": {
                "description": "verify auth token from firebase",
                "produces": [
                    "application/json"
                ],
                "summary": "verify auth token from firebase",
                "operationId": "verify-token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VerifyTokenResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GetUserLikesResponse": {
            "type": "object",
            "required": [
                "error",
                "likes"
            ],
            "properties": {
                "error": {
                    "type": "string"
                },
                "likes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Like"
                    }
                }
            }
        },
        "ListingsResponse": {
            "type": "object",
            "required": [
                "listings"
            ],
            "properties": {
                "listings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Listing"
                    }
                }
            }
        },
        "UpdateUserLikeResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "UserResponse": {
            "type": "object",
            "required": [
                "error",
                "user"
            ],
            "properties": {
                "error": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.UserRecord"
                }
            }
        },
        "VerifyTokenResponse": {
            "type": "object",
            "required": [
                "error",
                "verified"
            ],
            "properties": {
                "error": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                }
            }
        },
        "auth.UserInfo": {
            "type": "object",
            "required": [
                "displayName",
                "email",
                "phoneNumber",
                "photoUrl",
                "providerId",
                "rawId"
            ],
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "photoUrl": {
                    "type": "string"
                },
                "providerId": {
                    "description": "In the ProviderUserInfo[] ProviderID can be a short domain name (e.g. google.com),\nor the identity of an OpenID identity provider.\nIn UserRecord.UserInfo it will return the constant string \"firebase\".",
                    "type": "string"
                },
                "rawId": {
                    "type": "string"
                }
            }
        },
        "auth.UserMetadata": {
            "type": "object",
            "properties": {
                "creationTimestamp": {
                    "type": "integer"
                },
                "lastLogInTimestamp": {
                    "type": "integer"
                },
                "lastRefreshTimestamp": {
                    "description": "The time at which the user was last active (ID token refreshed), or 0 if\nthe user was never active.",
                    "type": "integer"
                }
            }
        },
        "auth.UserRecord": {
            "type": "object",
            "required": [
                "displayName",
                "email",
                "phoneNumber",
                "photoUrl",
                "providerId",
                "rawId"
            ],
            "properties": {
                "customClaims": {
                    "type": "object",
                    "additionalProperties": true
                },
                "disabled": {
                    "type": "boolean"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "emailVerified": {
                    "type": "boolean"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "photoUrl": {
                    "type": "string"
                },
                "providerId": {
                    "description": "In the ProviderUserInfo[] ProviderID can be a short domain name (e.g. google.com),\nor the identity of an OpenID identity provider.\nIn UserRecord.UserInfo it will return the constant string \"firebase\".",
                    "type": "string"
                },
                "providerUserInfo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/auth.UserInfo"
                    }
                },
                "rawId": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                },
                "tokensValidAfterMillis": {
                    "description": "milliseconds since epoch.",
                    "type": "integer"
                },
                "userMetadata": {
                    "$ref": "#/definitions/auth.UserMetadata"
                }
            }
        },
        "database.Address": {
            "type": "object",
            "required": [
                "city",
                "distance",
                "latitude",
                "line1",
                "line2",
                "longitude",
                "state",
                "zip"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "distance": {
                    "type": "number"
                },
                "latitude": {
                    "type": "number"
                },
                "line1": {
                    "type": "string"
                },
                "line2": {
                    "type": "string"
                },
                "longitude": {
                    "type": "number"
                },
                "state": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "database.Image": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "database.Like": {
            "type": "object",
            "required": [
                "createdAt",
                "listingId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "listingId": {
                    "type": "string"
                }
            }
        },
        "database.Listing": {
            "type": "object",
            "required": [
                "address",
                "availabilityDate",
                "available",
                "bathrooms",
                "bedrooms",
                "createdAt",
                "description",
                "id",
                "images",
                "rent",
                "source",
                "squareFootage",
                "updatedAt"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/database.Address"
                },
                "availabilityDate": {
                    "type": "string"
                },
                "available": {
                    "type": "boolean"
                },
                "bathrooms": {
                    "type": "number"
                },
                "bedrooms": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Image"
                    }
                },
                "rent": {
                    "type": "integer"
                },
                "source": {
                    "$ref": "#/definitions/database.Source"
                },
                "squareFootage": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "database.Source": {
            "type": "object",
            "required": [
                "site",
                "url"
            ],
            "properties": {
                "site": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Web App Template API",
	Description:      "This is a sample api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
